// Error codes — derived from contracts/error-codes.json.

export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_INVALID_REDIRECT: "AUTH_INVALID_REDIRECT",
  AUTH_STATE_MISMATCH: "AUTH_STATE_MISMATCH",
  AUTH_CODE_INVALID: "AUTH_CODE_INVALID",
  AUTH_TOKEN_REVOKED: "AUTH_TOKEN_REVOKED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  DOC_PATH_CONFLICT: "DOC_PATH_CONFLICT",
  EDIT_PRECONDITION_FAILED: "EDIT_PRECONDITION_FAILED",
  YJS_UPDATE_TOO_LARGE: "YJS_UPDATE_TOO_LARGE",
  PRECONDITION_REQUIRED: "PRECONDITION_REQUIRED",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  AI_COMMIT_UNAVAILABLE: "AI_COMMIT_UNAVAILABLE",
  DISK_WRITE_FAILED: "DISK_WRITE_FAILED",
  UPGRADE_REQUIRED: "UPGRADE_REQUIRED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
