export type {
  AcceptInviteRequest,
  AclOverride,
  AddCommentMessageRequest,
  AddTagsRequest,
  ApiRequestOptions,
  AuthLogoutRequest,
  AuthRefreshRequest,
  AuthRefreshResponse,
  CreateAclOverrideRequest,
  CreateCommentRequest,
  CreateDocumentRequest,
  CreateShareLinkRequest,
  CreateWorkspaceRequest,
  InviteToWorkspaceRequest,
  OAuthCallbackRequest,
  OAuthCallbackResponse,
  OAuthStartRequest,
  OAuthStartResponse,
  PagedResponse,
  RelayErrorEnvelope,
  ReopenCommentRequest,
  ResolveCommentRequest,
  ScriptumApiClientOptions,
  SearchDocumentResult,
  UpdateDocumentRequest,
  UpdateShareLinkRequest,
  UpdateWorkspaceRequest,
  WorkspaceMember,
} from "./api/client";
export {
  ScriptumApiClient,
  ScriptumApiError,
} from "./api/client";
export {
  acceptInvite,
  addCommentMessage,
  addTags,
  authLogout,
  authOAuthCallback,
  authOAuthStart,
  authTokenRefresh,
  createAclOverride,
  createComment,
  createDocument,
  createShareLink,
  createSyncSession,
  createWorkspace,
  deleteAclOverride,
  deleteDocument,
  getDocument,
  getWorkspace,
  inviteToWorkspace,
  listComments,
  listDocuments,
  listMembers,
  listWorkspaces,
  removeMember,
  reopenComment,
  resolveComment,
  searchDocuments,
  updateDocument,
  updateMember,
  updateShareLink,
  updateWorkspace,
} from "./api/endpoints";
export type {
  AgentClaimMode,
  AgentClaimParams,
  AgentClaimResult,
  AgentConflictsParams,
  AgentConflictsResult,
  AgentListParams,
  AgentListResult,
  AgentStatusParams,
  AgentStatusResult,
  AgentWhoamiParams,
  AgentWhoamiResult,
  DocBundleParams,
  DocBundleResult,
  DocDiffParams,
  DocDiffResult,
  DocHistoryParams,
  DocHistoryResult,
  DocEditParams,
  DocEditResult,
  DocReadParams,
  DocReadResult,
  DocSearchParams,
  DocSearchResult,
  DocSectionsParams,
  DocSectionsResult,
  DocTreeParams,
  DocTreeResult,
  GitConfigureParams,
  GitConfigureResult,
  GitStatusParams,
  GitStatusResult,
  GitSyncJobStatus,
  GitSyncMode,
  GitSyncParams,
  GitSyncPolicy,
  GitSyncResult,
  JsonRpcError,
  JsonRpcId,
  JsonRpcRequest,
  JsonRpcResponse,
  JsonRpcSuccessResponse,
  RpcMethod,
  RpcParamsMap,
  RpcResultMap,
  RpcWorkspace,
  WorkspaceCreateParams,
  WorkspaceCreateResult,
  WorkspaceListParams,
  WorkspaceListResult,
  WorkspaceOpenParams,
  WorkspaceOpenResult,
  YjsOps,
} from "./protocol/rpc";
export type {
  AckMessage,
  AwarenessPeer,
  AwarenessUpdateMessage,
  ErrorMessage,
  HelloAckMessage,
  HelloMessage,
  SnapshotMessage,
  SubscribeMessage,
  WsMessage,
  WsMessageType,
  YjsUpdateMessage,
} from "./protocol/ws";
export type { Agent } from "./types/agent";
export type { CommentMessage, CommentThread } from "./types/comment";
export type { Document } from "./types/document";
export type { Section } from "./types/section";
export type { ShareLink, SyncSession } from "./types/sync";
export type {
  Workspace,
  WorkspaceAgentsConfig,
  WorkspaceAppearanceConfig,
  WorkspaceConfig,
  WorkspaceDensity,
  WorkspaceEditorConfig,
  WorkspaceEditorFontFamily,
  WorkspaceGeneralConfig,
  WorkspaceGitSyncConfig,
  WorkspacePermissionsConfig,
  WorkspaceTheme,
} from "./types/workspace";
export {
  DAEMON_LOCAL_HOST,
  DAEMON_LOCAL_PORT,
  DAEMON_WHOAMI_URL,
  DAEMON_YJS_WS_URL,
} from "./contracts/daemon-ports";
export { ERROR_CODES, type ErrorCode } from "./contracts/error-codes";
export {
  DEFAULT_ASSIGNABLE_ROLES,
  WORKSPACE_ROLES,
  type WorkspaceDefaultRole,
  type WorkspaceRole,
} from "./contracts/roles";
export { STORAGE_KEYS, type StorageKey } from "./contracts/storage-keys";
